[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#d6dbe5"
blue = "#1081d6"
cyan = "#0f7ddb"
green = "#1dd361"
magenta = "#5350b9"
red = "#de352e"
white = "#ffffff"
yellow = "#f3bd09"

[colors.cursor]
cursor = "#b9b9b9"
text = "#101010"

[colors.normal]
black = "#1f1f1f"
blue = "#2a84d2"
cyan = "#1081d6"
green = "#2dc55e"
magenta = "#4e5ab7"
red = "#f81118"
white = "#d6dbe5"
yellow = "#ecba0f"

[colors.primary]
background = "#131313"
foreground = "#d6dbe5"

[colors.selection]
background = "#1f1f1f"
text = "#d6dbe5"

[cursor.style]
blinking = "Off"
shape = "Underline"

[font]
size = 18.0

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"

[window.dimensions]
columns = 120
lines = 60
